script: "server"
event-result: false
see-also: "/tutorials/recipes, $ServerEvents/tags, $ServerEvents/afterRecipes, $ServerEvents/compostableRecipes, $ServerEvents/recipeTypeRegistry, $ServerEvents/specialRecipeSerializers"